spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(fseVl/kjQro73HC57u6NjE2O4xU6YGL4u+w/kXvFGJyo6r/iztXced7Xo0bX1CaKtm5hzxcgBXQwTbzeBCRjp5tgSgsc50vxrjalABiTgAHQ5kR3r0YzN9fFhpH9j9MwwogudpZdI4lB1xS7nomNWLybKOGoOO7OIylkrDKHdESjo70zFqkGtaKabvG/1vzB)
    username: ENC(JrJ21s5aralF/ltdr8I19Q==)
    password: ENC(Cgr8Tm+Xc3geCmGWekqZ9VsjOHjZCg4p)

  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: secret

jwt:
  secret: ENC(D/J3tK1EsFjPnY9dcx50UUSzNzB5tTleAlexxN3r3wkA8sqpgJRMI2FLQ42o2ULv4yRTpdHetU+chCDq6VyHldYOLo7dW2J9gtM2kRERjRhDxczv4yBK2mpVrfp5/q5KdCGqitwAjP0qWi5vX4ho6VUIoMaMiCocHDZeBCn7nWs=)

redis:
  host: ENC(8HcjYIVnkeDGkkPUQ3+cB8wLAwqDOdPd)
  port: ENC(abmpN3SWG3scsGG4F6VJbw==)
  password: ENC(xr9ZvfQtVGCxlbymLxNPXG4Qxyl40IA9)

eid:
  key: ENC(B9cwrrg05EC+WNRxW6m2+Pa42w1VqM0nn/PDdnKh5sMgZKppvQQ9TeiWpeNpRl1PaHNESHCW8xlub/YIl2wO1PKA0bPBlBT++6Ec0plkA6w4pKowNPYWnguoWDe2pjQaUegJ6c8/A/Y=)

naver:
  cloud:
    sms:
      access-key: ENC(zjEjrY5/JsH1bUundGSsuQ8W9OL5gbp4y7JbnUebQo8=)
      secret-key: ENC(QS1ogRTUMC7tb1ZjleWlfaq1YuRmNfyNO94wbSuPXxEk4Eiayg+AhlpaubPNjjkIZPKQch+zYww=)
      serviceId: ENC(id/wfOp2l+sIem4dBPwjHb9ma+os8If2Yf9pQvn6eJIyZwAkzq2bYQ==)
      send-phone: ENC(4BV7f36IyQC2eHb6Z3+P6rwFeBuZAweR)

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
