name: Build 

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - run: touch ./src/main/resources/application-secret.yaml
      - run: echo "${{ secrets.DB_SECRET }}" > ./src/main/resources/application-secret.yaml
      - run: cat ./src/main/resources/application-secret.yaml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and no Test
        run: ./gradlew build -x test
